"""Versioned schema contract for cumulative lifecycle records."""

LIFECYCLE_SCHEMA = {
    "schema_version": "1.1",
    "required": [
        "stage_id",
        "objective",
        "previous_knowledge_consumed",
        "baseline",
        "expected_improvement",
        "measurement",
        "validation",
        "failure_analysis",
        "knowledge_extraction",
        "regression",
        "decision",
        "knowledge_carried_forward",
    ],
    "knowledge_statuses": [
        "FACT",
        "VERIFIED",
        "SUPPORTED",
        "HYPOTHESIS",
        "ASSUMPTION",
        "UNRESOLVED",
        "REJECTED",
    ],
    "quality_vector": [
        "accuracy",
        "correctness",
        "speed",
        "efficiency",
        "reliability",
        "robustness",
        "coverage",
        "reproducibility",
        "scientific_validity",
    ],
    "performance_metrics": [
        "runtime",
        "throughput",
        "latency",
        "memory",
        "cpu_utilization",
        "gpu_utilization",
        "io",
        "batch_efficiency",
        "feature_generation_time",
        "inference_time",
    ],
    "process_metrics": [
        "lifecycle_contract_coverage",
        "knowledge_artifact_count",
        "regression_protection_count",
        "audit_time",
        "implementation_time",
        "debugging_time",
        "regression_fix_time",
        "rework_count",
        "repeated_failure_count",
        "pr_cycle_time",
        "test_execution_efficiency",
    ],
    "decisions": ["ACCEPT", "REVISE", "BLOCKED"],
}
